let name=document.getElementById("name")
let age=document.getElementById("age")
let gender=document.getElementById("gender")
let phNumber=document.getElementById("phNumber")
let email=document.getElementById("email")
